version: "3"

services:
  nginx:    
    build: ./nginx/  
    container_name: nginx-container  
    ports:  
      - 8000:80  
    links:  
      - php  
    volumes_from:  
      - app-data  

  php:    
    build:
      context: ./php/
      args:
        user: hanif # your username (echo $USER)
        uid: 1000 # your uid (id -u)
    container_name: php-container  
    expose:  
      - 9000  
    links:  
      - mysql
    working_dir: /var/www/html/
    volumes_from:  
      - app-data 

  util:    
    build:
      context: ./php/
      args:
        user: hanif # your username (echo $USER)
        uid: 1000 # your uid (id -u)
    container_name: util-container  
    expose:  
      - 9000  
    links:  
      - mysql
    working_dir: /var/www/html/
    command: >
      sh -c "composer install && 
             php artisan config:clear && php artisan cache:clear &&
             php artisan queue:listen > /var/www/html/storage/logs/queue.log"
    volumes_from:  
      - app-data

  node:    
    image: node:14.19.3-alpine3.16
    container_name: node-container
    command: >
      sh -c "npm install &&
             npm run watch"
    working_dir: /var/www/html
    volumes_from:  
      - app-data  

  app-data:    
    image: php:7.3-fpm
    container_name: app-data-container  
    volumes:  
      - ./www/html/:/var/www/html/  
    command: "true"

  mysql:    
    image: mysql:5.7  
    container_name: mysql-container
    volumes_from:
      - mysql-data
    ports:
      - 3307:3306
    environment:  
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kyx  
      MYSQL_USER: secret  
      MYSQL_PASSWORD: secret

  mysql-data:    
    image: mysql:5.7  
    container_name: mysql-data-container  
    volumes:  
      - /var/lib/mysql
      - ./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    command: "true"

  mailhog: # https://aregsar.com/blog/2020/laravel-app-with-mail-server-in-docker/
    image: mailhog/mailhog:latest
    container_name: mailhog-container
    ports:
      - "8003:1025"
      - "8100:8025" # http://127.0.0.1:8100/

  ngrok:
    image: shkoliar/ngrok:latest
    container_name: ngrok-container
    ports:
      - 4551:4551 # http://127.0.0.1:4551
    links:
      - nginx
    environment:
      - DOMAIN=nginx
      - PORT=80
      - AUTH_TOKEN=256c916GK48qaOTmzd0tWdXe0lj_2ArUz1vj4P54gjq3yUe5j