version: "3"

services:
  nginx:    
    build: ./nginx/  
    container_name: nginx-container
    restart: always
    ports:  
      - ${HOST_PORT}:80  
    links:  
      - app  
    volumes_from:  
      - app
    depends_on:
      - app

  app:    
    build:
      context: ./php/
      args:
        user: ${HOST_USER} # your username (echo $USER)
        uid: ${HOST_UID} # your uid (id -u)
        php_version: ${PHP_VERSION}
    image: app:latest
    container_name: app-container
    environment:
      APP_ENV: ${APP_ENV}
      CONTAINER_ROLE: app
    restart: always
    expose:  
      - 9000  
    working_dir: /var/www/html/
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:  
      - ${WORK_DIR}:/var/www/html/
    depends_on:
      - mysql

  scheduler:    
    image: app:latest
    container_name: scheduler-container
    environment:
      APP_ENV: ${APP_ENV}
      CONTAINER_ROLE: scheduler
    restart: always
    command: "/usr/local/bin/start.sh"
    working_dir: /var/www/html/
    volumes_from:  
      - app
    depends_on:
      - app
  
  queue:    
    image: app:latest
    container_name: queue-container
    environment:
      APP_ENV: ${APP_ENV}
      CONTAINER_ROLE: queue
    restart: always
    command: "/usr/local/bin/start.sh"
    working_dir: /var/www/html/
    volumes_from:  
      - app
    depends_on:
      - app

  composer:    
    image: app:latest
    container_name: composer-container
    environment:
      APP_ENV: ${APP_ENV}
      CONTAINER_ROLE: composer
    # restart: always
    command: "/usr/local/bin/start.sh"
    working_dir: /var/www/html/
    volumes_from:  
      - app
    depends_on:
      - app

  node:    
    image: node:${NODE_VERSION}
    container_name: node-container
    restart: always
    command: >
      sh -c "echo fs.inotify.max_user_instances=524288 && sysctl -p && 
             npm install &&
             npm run watch -s
             "
    working_dir: /var/www/html
    volumes:  
      - ${WORK_DIR}:/var/www/html/

  mysql:    
    image: mysql:${MYSQL_VERSION}  
    container_name: mysql-container
    restart: always
    volumes:
      - volume_mysql:/var/lib/mysql
      - ${SQL_DUMP_FILE}:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - ${MYSQL_PORT}:3306
    environment:  
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}  
      MYSQL_USER: ${MYSQL_USER}  
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  mailhog: # https://aregsar.com/blog/2020/laravel-app-with-mail-server-in-docker/
    image: mailhog/mailhog:latest
    container_name: mailhog-container
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH="/maildir"
    restart: always
    volumes:
      - volume_mailhog:/maildir
    ports:
      - "8003:1025"
      - ${MAILHOG_PORT}:8025 # http://127.0.0.1:8100/

  ngrok:
    image: shkoliar/ngrok:latest
    container_name: ngrok-container
    restart: always
    ports:
      - ${NGROK_PORT}:4551 # http://127.0.0.1:4551
    links:
      - nginx
    environment:
      - DOMAIN=nginx
      - PORT=80
      - AUTH_TOKEN=${NGROK_AUTH_TOKEN}

volumes:
  volume_mailhog:
  volume_mysql: